version: "3"

services:

#  apache:
#    container_name: realworld_apache
#    build:
#      context: .
#      dockerfile: .docker/apache.dockerfile
#    depends_on:
#      - drash
#    ports:
#      - "8080:80"
#    networks:
#      - drash-app-network

#  postgres:
#    image: "postgres:11"
#    container_name: "realworld_postgres"
#    ports:
#      - "54320:5432"
#    environment:
#      - POSTGRES_USER=user
#      - POSTGRES_PASSWORD=userpassword
#      - POSTGRES_DB=realworld
#    networks:
#      - drash-app-network

  drash:
    container_name: realworld_drash
    working_dir: /var/www/src
    build:
      context: .
      dockerfile: .docker/drash.dockerfile
    command: bash -c "cd /var/www/src && deno run -A --watch --unstable app.ts"
    volumes:
      - ./src/config:/var/www/src/config
      - ./src/db:/var/www/src/db
      - ./src/middlewares:/var/www/src/middlewares
      - ./src/models:/var/www/src/models
      - ./src/resources:/var/www/src/resources
      - ./src/services:/var/www/src/services
      - ./src/tests:/var/www/src/tests
      - ./src/vue:/var/www/src/vue
      - ./src/config.ts:/var/www/src/config.ts
      - ./src/app.ts:/var/www/src/app.ts
      - ./src/deps.ts:/var/www/src/deps.ts
      - ./src/nessie.config.ts:/var/www/src/nessie.config.ts
      - ./src/package.json:/var/www/src/package.json
      - ./src/package-lock.json:/var/www/src/package-lock.json
      - ./src/server.ts:/var/www/src/server.ts
      - ./src/webpack.config.js:/var/www/src/webpack.config.js
      - ./src/.env:/var/www/src/.env
    ports:
      - "1667:1667"
    networks:
      - drash-app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - drash
    networks:
      - drash-app-network

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: /bin/sh -c
    command: >
      "certbot certonly --webroot 
      --webroot-path=/var/www/certbot 
      --email martinoli944@gmail.com 
      --agree-tos 
      --no-eff-email 
      -d drash.app.erickprojects.xyz -d www.drashapp.erickprojects.xyz"
networks:
  drash-app-network:
    driver: bridge
