name: Deploy to EC2

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    name: Deploy Docker App to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e

            cd ~/realworld-project  # or wherever your code lives

            echo "Updating code..."
            git pull origin main

            echo "Injecting .env file..."
            cat <<EOT > ./src/.env
            DB_HOSTNAME=${{ secrets.DB_HOST }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_DATABASE=${{ secrets.DB_NAME }}
            PGPORT=5432
            EOT

            echo "Stopping and rebuilding containers..."
            docker compose down
            docker compose build
            docker compose up -d

            echo "Deployment complete!"
          EOF
