name: Deploy to EC2

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    name: Deploy Docker App to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          username: ${{secrets.EC2_USER}}
          script: |
            set -e
            cd /home/ubuntu/deno-drash-realworld-example-app
            echo "Updating code..."
            git pull origin main

            echo "Injecting .env file..."
            cat <<EOT > ./src/.env
            DB_HOSTNAME=${{ secrets.DB_HOST }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_DATABASE=${{ secrets.DB_NAME }}
            PGPORT=5432
            EOT

            echo "Stopping and rebuilding containers..."
            docker compose down || true
            docker compose build
            docker compose up -d nginx drash
            
            docker compose run --rm certbot certonly --webroot --webroot-path=/var/www/certbot \
            -d drash.app.erickprojects.xyz -d www.drashapp.erickprojects.xyz --email ${{secrets.CERBOT_EMAIL}} --agree-tos --no-eff-email
            
            docker compose restart nginx


            echo "✅ Deployment complete!"
